# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20191012_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageUrl',
        ),
    ]
